### ISSUE TITLE
Carrito

### ISSUE THREAD

**Issue by Nidev-lab** [IgnacioVelazquez92/AM-FRONT-PF#27]
## Proceso

1. Ingrese con un usuario.
2. Seleccione algunos productos a comprar.

## Resultado esperado

Que al hacer click en "Comprar" mi compra se realice.

## Resultado actual

• Al hacer click en "Comprar" no sucede nada.

## Captura

![image](https://github.com/IgnacioVelazquez92/AM-FRONT-PF/assets/53904695/cd6e8cbb-1894-4fbe-ab57-ac649a7f756c)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Una posible solucion seria que al hacer click en comprar se abra un modal diciendo que la compra se realizo con exito.

**Comment by IgnacioVelazquez92** [comment]
Hola nico como estas? , realice algo similar a la solución que planteaste, desde ya muchas gracias!
